name: CI

on: push

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.6.1
      
      - name: Construcao da imagem docker
        uses: docker/build-push-action@v6.9.0
        with:
          username: ${{secrets.dockerusr}}
          password: ${{secrets.dockerpwd}}

          context: ./src
          file: ./Dockerfile
          push: true
          tags: |
            binho6/potfolio:${{github.run_number}}
            binho6/potfolio:latest
          platforms: linux/arm64
      
